### PR TITLE
fixed variable defaults and Readme

### PR DESCRIPTION
**Pull request by radhikabhat08**
This change is [Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-stcv/2)

### CODE REVIEW

**Review by rmyers808 — CHANGES_REQUESTED** [review]
Sorry, docs changed recently.  Please update to latest terraform_aws_stcv and terraform_vsphere_aion.  I added comments to README.md

> Reviewed 2 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-stcv/2#-:-MUL0N-3-sKp02easupm:b-77rztz)* status: 2 of 6 files reviewed, 3 unresolved discussions (waiting on @jhiga, @ltran-spirent, and @radhikabhat08)

___
*[README.md, line 17 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-stcv/2#-MUKPTfv18w2UtpV_xBj:-MUKPTfv18w2UtpV_xBk:bvpv7ac) ([raw file](https://github.com/spirent-terraform-modules/terraform-vsphere-stcv/blob/193bfffff44370ed8bfc717d25287f13b12173ee/README.md#L17)):*
> ```Markdown
> [govc](https://github.com/vmware/govmomi/tree/master/govc) is a vSphere command line interface (CLI). Follow installation instructions [here](https://github.com/vmware/govmomi/tree/master/govc#Installation).
> 
> Set govc environmental variables specific to your vSphere: GOVC_URL, GOVC_INSECURE, GOVC_USERNAME, GOVC_PASSWORD
> ```

Can you update this to: `GOVC_URL`, `GOVC_INSECURE`, `GOVC_USERNAME`, `GOVC_PASSWORD`
___
*[examples/run-stcv/README.md, line 3 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-stcv/2#-MUL-ZcR6zr4Z0v6YsEl:-MUL-ZcS92AbEe2sERls:bnq6pf3) ([raw file](https://github.com/spirent-terraform-modules/terraform-vsphere-stcv/blob/193bfffff44370ed8bfc717d25287f13b12173ee/examples/run-stcv/README.md#L3)):*
> ```Markdown
> ## Description
> This Terraform module deploys Spirent TestCenter Virtual Machines from a template created from the ova file.
> The example requires the user to provide an already existing datacenter , datastore, network , OVF template details .
> ```

Remove space after "datacenter" and "details"
___
*[examples/run-stcv/README.md, line 14 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-stcv/2#-MUL-gIA-gJ9dn6fr2oa:-MUL-gIA-gJ9dn6fr2ob:bwr6rp1) ([raw file](https://github.com/spirent-terraform-modules/terraform-vsphere-stcv/blob/193bfffff44370ed8bfc717d25287f13b12173ee/examples/run-stcv/README.md#L14)):*
> ```Markdown
>     $ terraform apply
> 
> _Note: [Prerequisites](../../README.md#Prerequisites) are also required._
> ```

Update to latest terraform_aws_stcv & terraform_vsphere_aion.

This example will create resources that will incur a cost. Run `terraform destroy` when you don't need these resources.

**Note:** [Prerequisites](../../README.md#Prerequisites) are also required.

**Review by jhiga — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-stcv/2)* status: 4 of 6 files reviewed, 5 unresolved discussions (waiting on @ltran-spirent and @radhikabhat08)

___
*[README.md, line 31 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-stcv/2#-MULExtjEYsc8v7iwHPQ:-MULExtjEYsc8v7iwHPR:bxpkdht) ([raw file](https://github.com/spirent-terraform-modules/terraform-vsphere-stcv/blob/193bfffff44370ed8bfc717d25287f13b12173ee/README.md#L31)):*
> ```Markdown
> ```
> 
> 
> ```

Please update your local pre-commit-related tooling per Richard's confluence page he referenced in slack.
___
*[README.md, line 84 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-stcv/2#-MULEltL-ftGC2tT2Njz:-MULEltME47LoDs99vsx:b2ti6vx) ([raw file](https://github.com/spirent-terraform-modules/terraform-vsphere-stcv/blob/193bfffff44370ed8bfc717d25287f13b12173ee/README.md#L84)):*
> ```Markdown
> | Name | Description |  Type | Default
> |------|-------------|-------------|-------------
> | speed | Maximum network interface speed | 1G, 5G, 10G, 25G, 50G, 100G | 1G
> ```

please update this section to match what's on `terraform-aws-stcv`.  fixes some typos.

**Review by jhiga — APPROVED** [review]
:lgtm:

> Reviewed 1 of 6 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-stcv/2#-:-MUN5i9j8pfeRJ1LL9ey:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @ltran-spirent and @radhikabhat08)

**Review by rmyers808 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-stcv/2#-:-MUPM0FUC7WLNmhbUjvV:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ltran-spirent and @radhikabhat08)

**Pull request merged**
