### PR TITLE
added new vsphere stcv deployment script

### PR DESCRIPTION
**Pull request by radhikabhat08**
This change is [Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-stcv/1)

### CODE REVIEW

**Review by radhikabhat08 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-stcv/1)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @jhiga, @ltran-spirent, and @rmyers808)

___
*[main.tf, line 32 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-stcv/1#-MTB_R_t8rQUdeK0zAjf:-MTB_R_t8rQUdeK0zAjg:bi5zg7o) ([raw file](https://github.com/spirent-terraform-modules/terraform-vsphere-stcv/blob/9d76d59478c4c6f82f8b132d4dfa7429e797912d/main.tf#L32)):*
> ```HCL
>   }
> 
>   extra_config = {
> ```

TODO - this userdata config is yet not reflecting on the VM.

**Review by jhiga — CHANGES_REQUESTED** [review]
Where's the `version.tf` that contains the provider and required versions?

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-stcv/1#-:-MTCAG563lJhwuNefzt7:ba786e5)* status: all files reviewed, 2 unresolved discussions (waiting on @ltran-spirent, @radhikabhat08, and @rmyers808)

___
*[examples/run-stcv/variable.tf, line 3 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-stcv/1#-MTC8myG2F8i7VzogiBU:-MTC8myG2F8i7VzogiBV:b-5ynp00) ([raw file](https://github.com/spirent-terraform-modules/terraform-vsphere-stcv/blob/9d76d59478c4c6f82f8b132d4dfa7429e797912d/examples/run-stcv/variable.tf#L3)):*
> ```HCL
> variable "vsphere_server" {
>   description = "The vSphere server."
>   default     = "virttest-vc.calenglab.spirentcom.com"
> ```

please don't use real values as this is a public repo (multiple occurrences in this file).

**Comment by jhiga** [comment]
___
*[README.md, line 1 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-stcv/1#-MTCAgLtDrthixolIdW0:-MTCAgLtDrthixolIdW1:buo5z80) ([raw file](https://github.com/spirent-terraform-modules/terraform-vsphere-stcv/blob/9d76d59478c4c6f82f8b132d4dfa7429e797912d/README.md#L1)):*
> ```Markdown
> # Run STCv traffic generator instances with public and test networks. Instances can be controlled by the Spirent TestCenter application.
> ```

We should include a section with the STCv user data as we currently do for AWS, for example.

https://github.com/Spirent-Terraform-Modules/terraform-aws-stcv#user-data-cloud-init

**Review by rmyers808 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-stcv/1)* status: all files reviewed, 4 unresolved discussions (waiting on @ltran-spirent and @radhikabhat08)

___
*[variables.tf, line 4 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-stcv/1#-MTDTYFD3kKJDnxxVSNu:-MTDTYFD3kKJDnxxVSNv:bd6v2y5) ([raw file](https://github.com/spirent-terraform-modules/terraform-vsphere-stcv/blob/9d76d59478c4c6f82f8b132d4dfa7429e797912d/variables.tf#L4)):*
> ```HCL
>   description = "The vSphere server."
>   type        = string
>   default     = ""
> ```

I think it is better to not include default instead of empty string for variables that need to be filled in the main modules variables.

**Review by rmyers808 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-stcv/1)* status: all files reviewed, 4 unresolved discussions (waiting on @ltran-spirent and @radhikabhat08)

___
*[variables.tf, line 4 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-stcv/1#-MTDTYFD3kKJDnxxVSNu:-MTDU3maBUk-uFlom9dU:b-bx1gtn) ([raw file](https://github.com/spirent-terraform-modules/terraform-vsphere-stcv/blob/9d76d59478c4c6f82f8b132d4dfa7429e797912d/variables.tf#L4)):*
<details><summary><i>Previously, rmyers808 (Richard Myers) wrote…</i></summary><blockquote>

I think it is better to not include default instead of empty string for variables that need to be filled in the main modules variables.
</blockquote></details>

This applies to: vsphere_user, vsphere_password, vsphere_datacenter, vsphere_datastore, vsphere_host, vsphere_compute_cluster, template_name, datastore_id, resource_pool_id, mgmt_plane_network_id, data_plane_network_id

**Review by rmyers808 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-stcv/1)* status: all files reviewed, 4 unresolved discussions (waiting on @ltran-spirent and @radhikabhat08)

___
*[variables.tf, line 4 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-stcv/1#-MTDTYFD3kKJDnxxVSNu:-MTDVzY870dJZ49XWr5_:b-nr7ogn) ([raw file](https://github.com/spirent-terraform-modules/terraform-vsphere-stcv/blob/9d76d59478c4c6f82f8b132d4dfa7429e797912d/variables.tf#L4)):*
<details><summary><i>Previously, rmyers808 (Richard Myers) wrote…</i></summary><blockquote>

This applies to: vsphere_user, vsphere_password, vsphere_datacenter, vsphere_datastore, vsphere_host, vsphere_compute_cluster, template_name, datastore_id, resource_pool_id, mgmt_plane_network_id, data_plane_network_id
</blockquote></details>

Are these vsphere_* varaibles used?

**Comment by radhikabhat08** [comment]
___
*[variables.tf, line 4 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-stcv/1#-MTDTYFD3kKJDnxxVSNu:-MTEBGHK4oW8ePyoR0xf:bajtpjc) ([raw file](https://github.com/spirent-terraform-modules/terraform-vsphere-stcv/blob/9d76d59478c4c6f82f8b132d4dfa7429e797912d/variables.tf#L4)):*
<details><summary><i>Previously, rmyers808 (Richard Myers) wrote…</i></summary><blockquote>

Are these vsphere_* varaibles used?
</blockquote></details>

these variables are used in example, but I thought of leaving them in main variables for visibility. but yeah will remove them if it is more confusing.

**Comment by radhikabhat08** [comment]
For the version file , I could not find any good example that adds the vsphere version requirement.

**Review by radhikabhat08 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-stcv/1)* status: 1 of 7 files reviewed, 4 unresolved discussions (waiting on @jhiga, @ltran-spirent, and @rmyers808)

___
*[README.md, line 1 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-stcv/1#-MTCAgLtDrthixolIdW0:-MTE8d2fCI68WqBahX3A:bgdyzin) ([raw file](https://github.com/spirent-terraform-modules/terraform-vsphere-stcv/blob/9d76d59478c4c6f82f8b132d4dfa7429e797912d/README.md#L1)):*
<details><summary><i>Previously, jhiga (Justin Higa) wrote…</i></summary><blockquote>

We should include a section with the STCv user data as we currently do for AWS, for example.

https://github.com/Spirent-Terraform-Modules/terraform-aws-stcv#user-data-cloud-init
</blockquote></details>

sure Justin, in plan as soon as able to 
___
*[examples/run-stcv/variable.tf, line 3 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-stcv/1#-MTC8myG2F8i7VzogiBU:-MTEqV1O-LVqD1y_6oU6:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-vsphere-stcv/blob/9d76d59478c4c6f82f8b132d4dfa7429e797912d/examples/run-stcv/variable.tf#L3)):*
<details><summary><i>Previously, jhiga (Justin Higa) wrote…</i></summary><blockquote>

please don't use real values as this is a public repo (multiple occurrences in this file).
</blockquote></details>

Done.

**Review by jhiga — CHANGES_REQUESTED** [review]
This is the latest version: https://registry.terraform.io/providers/hashicorp/vsphere/latest

Click the "Use Provider" button on that page for an example and you should end up with something like this for `version.tf`
```
terraform {
  required_version = ">= 0.13.0"

  required_providers {
    vsphere = {
      source = "hashicorp/vsphere"
      version = "1.24.3"
    }
  }
}
```

> Reviewed 6 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-stcv/1#-:-MTEwP-0EZGzrY87EHqs:b-28r15p)* status: all files reviewed, 3 unresolved discussions (waiting on @ltran-spirent, @radhikabhat08, and @rmyers808)

___
*[examples/run-stcv/main.tf, line 50 at r2](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-stcv/1#-MTEwBVp6vYIzwvINmOG:-MTEwBVqD7Tx-KOAGg1v:bs03i1x) ([raw file](https://github.com/spirent-terraform-modules/terraform-vsphere-stcv/blob/cb15d404124ce7ff36bc6b6a7bc9296373af39e3/examples/run-stcv/main.tf#L50)):*
> ```HCL
>   data_plane_network_id   = data.vsphere_network.data_plane.id
>   template_name           = var.template_name
>   user_data_file          = "../../cloud-init.yaml"
> ```

The `cloud-init.yaml` file is missing in the root of the repo.

**Review by radhikabhat08 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-stcv/1)* status: 5 of 10 files reviewed, 3 unresolved discussions (waiting on @jhiga, @ltran-spirent, and @rmyers808)

___
*[examples/run-stcv/main.tf, line 50 at r2](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-stcv/1#-MTEwBVp6vYIzwvINmOG:-MTFeh9v4v_w3qMxa3_3:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-vsphere-stcv/blob/cb15d404124ce7ff36bc6b6a7bc9296373af39e3/examples/run-stcv/main.tf#L50)):*
<details><summary><i>Previously, jhiga (Justin Higa) wrote…</i></summary><blockquote>

The `cloud-init.yaml` file is missing in the root of the repo.
</blockquote></details>

Done.

**Review by jhiga — APPROVED** [review]
> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-stcv/1)* status: all files reviewed, 2 unresolved discussions (waiting on @ltran-spirent and @rmyers808)

**Review by rmyers808 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r2, 2 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-stcv/1)* status: all files reviewed, 7 unresolved discussions (waiting on @ltran-spirent and @radhikabhat08)

___
*[variables.tf, line 28 at r3](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-stcv/1#-MTSVrrzEH3-vuOYiWEJ:-MTSVrrzEH3-vuOYiWEK:b-tiywed) ([raw file](https://github.com/spirent-terraform-modules/terraform-vsphere-stcv/blob/b519c633abde4d0fa3f156ebe80a9a11ff69da5c/variables.tf#L28)):*
> ```HCL
>   description = "Name of the template created from the OVA"
>   type        = string
>   default     = ""
> ```

Remove  default= ""
___
*[variables.tf, line 34 at r3](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-stcv/1#-MTSVy-OAfleHTAdmSnY:-MTSVy-OAfleHTAdmSnZ:b-tiywed) ([raw file](https://github.com/spirent-terraform-modules/terraform-vsphere-stcv/blob/b519c633abde4d0fa3f156ebe80a9a11ff69da5c/variables.tf#L34)):*
> ```HCL
>   description = "vSphere datacenter ID."
>   type        = string
>   default     = ""
> ```

Remove  default= ""
___
*[variables.tf, line 40 at r3](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-stcv/1#-MTSVylU4zEtmPVs-90O:-MTSVylU4zEtmPVs-90P:b-tiywed) ([raw file](https://github.com/spirent-terraform-modules/terraform-vsphere-stcv/blob/b519c633abde4d0fa3f156ebe80a9a11ff69da5c/variables.tf#L40)):*
> ```HCL
>   description = "vSphere datastore ID."
>   type        = string
>   default     = ""
> ```

Remove  default= ""
___
*[variables.tf, line 46 at r3](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-stcv/1#-MTSVzdZ05klhcY3e18P:-MTSVzdZ05klhcY3e18Q:b-tiywed) ([raw file](https://github.com/spirent-terraform-modules/terraform-vsphere-stcv/blob/b519c633abde4d0fa3f156ebe80a9a11ff69da5c/variables.tf#L46)):*
> ```HCL
>   description = "vSphere resource pool ID."
>   type        = string
>   default     = ""
> ```

Remove  default= ""
___
*[variables.tf, line 52 at r3](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-stcv/1#-MTSW-QTBu8O9_V4shrX:-MTSW-QTBu8O9_V4shrY:b-tiywed) ([raw file](https://github.com/spirent-terraform-modules/terraform-vsphere-stcv/blob/b519c633abde4d0fa3f156ebe80a9a11ff69da5c/variables.tf#L52)):*
> ```HCL
>   description = "Management network ID."
>   type        = string
>   default     = ""
> ```

Remove  default= ""
___
*[variables.tf, line 58 at r3](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-stcv/1#-MTSW0TW3jecY7vjGtIL:-MTSW0TW3jecY7vjGtIM:b-tiywed) ([raw file](https://github.com/spirent-terraform-modules/terraform-vsphere-stcv/blob/b519c633abde4d0fa3f156ebe80a9a11ff69da5c/variables.tf#L58)):*
> ```HCL
>   description = "Test or data plane network ID."
>   type        = string
>   default     = ""
> ```

Remove  default= ""

**Review by rmyers808 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-stcv/1)* status: all files reviewed, 7 unresolved discussions (waiting on @ltran-spirent and @radhikabhat08)

___
*[variables.tf, line 28 at r3](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-stcv/1#-MTSX-OuCKDY6s9Jy93a:-MTSX-OuCKDY6s9Jy93b:b6m3bqr) ([raw file](https://github.com/spirent-terraform-modules/terraform-vsphere-stcv/blob/b519c633abde4d0fa3f156ebe80a9a11ff69da5c/variables.tf#L28)):*
> ```HCL
>   description = "Name of the template created from the OVA"
>   type        = string
>   default     = ""
> ```

Remove default= "" or explain what it means when "" is used.
___
*[variables.tf, line 34 at r3](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-stcv/1#-MTSX0bc6F6nfmivicU_:-MTSX0bc6F6nfmivicUa:b6m3bqr) ([raw file](https://github.com/spirent-terraform-modules/terraform-vsphere-stcv/blob/b519c633abde4d0fa3f156ebe80a9a11ff69da5c/variables.tf#L34)):*
> ```HCL
>   description = "vSphere datacenter ID."
>   type        = string
>   default     = ""
> ```

Remove default= "" or explain what it means when "" is used.
___
*[variables.tf, line 40 at r3](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-stcv/1#-MTSX2-F1Vmh4K2gf2gp:-MTSX2-F1Vmh4K2gf2gq:b6m3bqr) ([raw file](https://github.com/spirent-terraform-modules/terraform-vsphere-stcv/blob/b519c633abde4d0fa3f156ebe80a9a11ff69da5c/variables.tf#L40)):*
> ```HCL
>   description = "vSphere datastore ID."
>   type        = string
>   default     = ""
> ```

Remove default= "" or explain what it means when "" is used.
___
*[variables.tf, line 46 at r3](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-stcv/1#-MTSWTnD8y3i6s_2dDo5:-MTSWTnD8y3i6s_2dDo6:b6m3bqr) ([raw file](https://github.com/spirent-terraform-modules/terraform-vsphere-stcv/blob/b519c633abde4d0fa3f156ebe80a9a11ff69da5c/variables.tf#L46)):*
> ```HCL
>   description = "vSphere resource pool ID."
>   type        = string
>   default     = ""
> ```

Remove default= "" or explain what it means when "" is used.
___
*[variables.tf, line 52 at r3](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-stcv/1#-MTSWufHEiAIu2-A9g-M:-MTSWufI3NU7_1LW3Da-:b6m3bqr) ([raw file](https://github.com/spirent-terraform-modules/terraform-vsphere-stcv/blob/b519c633abde4d0fa3f156ebe80a9a11ff69da5c/variables.tf#L52)):*
> ```HCL
>   description = "Management network ID."
>   type        = string
>   default     = ""
> ```

Remove default= "" or explain what it means when "" is used.
___
*[variables.tf, line 58 at r3](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-stcv/1#-MTSWw0GBSGGDkuzRKpg:-MTSWw0GBSGGDkuzRKph:b6m3bqr) ([raw file](https://github.com/spirent-terraform-modules/terraform-vsphere-stcv/blob/b519c633abde4d0fa3f156ebe80a9a11ff69da5c/variables.tf#L58)):*
> ```HCL
>   description = "Test or data plane network ID."
>   type        = string
>   default     = ""
> ```

Remove default= "" or explain what it means when "" is used.

**Review by rmyers808 — COMMENTED** [review]
Setting default = "" should only be done if it is a valid value.  Other than that it looks good to me. 

> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-vsphere-stcv/1#-:-MTSZyPY4JNVAsh89Emy:b-jvqyxc)* status: all files reviewed, 7 unresolved discussions (waiting on @ltran-spirent and @radhikabhat08)

**Pull request merged**
